version: 2
jobs:
    build:
        docker:
        - image: circleci/php:7.2-node-browsers

        steps:
            - checkout

            # Prepare for later installations
            - run:
                name: "Update apt"
                command: sudo apt-get update

            # Download and cache composer dependencies
            - restore_cache:
                keys:
                  # "composer.lock" can be used if it is committed to the repo
                  - v1-dependencies-{{ checksum "composer.json" }}
                  # fallback to using the latest cache if no exact match is found
                  - v1-dependencies-
            - run:
                name: "Run composer"
                command: composer install -n --prefer-dist
            - save_cache:
                key: v1-dependencies-{{ checksum "composer.json" }}
                paths:
                  - ./vendor

            # Download and cache npm dependencies
            - restore_cache:
                keys:
                  - node-v1-{{ checksum "package.json" }}
                  - node-v1-
            - run: yarn install
            - save_cache:
                key: node-v1-{{ checksum "package.json" }}
                paths:
                  - node_modules

            - run:
                name: "Run PHP Lint"
                command: find -L ./ -name '*.php' -not -path './wordpress/*' -print0 | xargs -0 -n 1 -P 4 php -l > /dev/null

            # Run phpcs
            - run:
                name: "Run phpcs"
                command: composer lint
